### PR TITLE
Recorder neuron

### PR DESCRIPTION
**Pull request by corus87**
A simple wave recorder e.g. to test and calibrate the microphone

### CODE REVIEW

**Comment by Sispheor** [comment]
Can you by the way fix links in the main page. I forgot those ones :)

**Comment by corus87** [comment]
Sure no problem, but what about the quickstart? I can't find it anymore.

**Comment by Sispheor** [comment]
Quick start too yes. It's getting started now on the new doc

**Comment by corus87** [comment]
And which URL should I use for quickstart? https://kalliope-project.github.io/kalliope/installation/quickstart ?

**Comment by Sispheor** [comment]
https://kalliope-project.github.io/kalliope/getting-started/

**Comment by Sispheor** [comment]
All links must refer the new doc

**Comment by corus87** [comment]
Sure the quickstart... Thought this was a quickstart to install Kalliope not for the brain^^

**Review by Sispheor — APPROVED** [review]

**Pull request merged**
