### PR TITLE
Adding "Gif-Maker" to Jekyll Build

### PR DESCRIPTION
**Pull request by slapker**
Adding Gif_maker neuron to the neuron_marketplace

### CODE REVIEW

**Comment by Sispheor** [comment]
Please only send a PR with modified data in the yaml file. Do not build the project. I'll do it.

**Comment by slapker** [comment]
Hi 

Ok I will do it. 

I'm still a beginner with good github practice, but I thinks that we may need more details on "how to" contribute for the kalliope website.

Just for my own information, can you confirm : 
- Fork https://github.com/kalliope-project/kalliope-project.github.io.git
- git init
- git remote add upstream https://github.com/kalliope-project/kalliope-project.github.io.git
- git pull upstream sources
- git remote add origin https://github.com/slapker/kalliope-project.github.io.git
- Modifying the YML to add neuron
- git add & git comit & git push origin sources
- Then doing the PR ?

Thanks !

**Comment by Sispheor** [comment]
- fork the repo in your github
- clone it
- checkout sources
- do your update
- commit and push
- then PR

And I recomand you the usage of an GIT IDE like GitKraken. Very useful for beginner.

**Comment by slapker** [comment]
Ok Thanks, I'll do that soon !

**Pull request closed without merging**
